#theme: jekyll-theme-midnight

url: "https://tlwt.github.io/SecDevOpsKb"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      sitetitle: "SCRATCh"
      subtitle: "a funded project"
      layout: default
