#theme: jekyll-theme-midnight

url: "https://github.com/tlwt/SecDevOpsKb/"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      sitetitle: "SCRATCh"
      subtitle: "a funded project"
      layout: default
